import "../style/index.css";
import localFont from "next/font/local";
import Navbar from "@/components/Navbar";
// import Footer from "@/components/shared/Footer";
// import SmoothScroll from "@/components/SmoothScroll";
// import PageTransition from "@/components/PageTransition";

const clashGrotesk = localFont({
  src: [
    {
      path: "/fonts/clash-grotesk/ClashGrotesk-Extralight.woff2",
      weight: "200",
      style: "normal",
    },
    {
      path: "/fonts/clash-grotesk/ClashGrotesk-Light.woff2",
      weight: "300",
      style: "normal",
    },
    {
      path: "/fonts/clash-grotesk/ClashGrotesk-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "/fonts/clash-grotesk/ClashGrotesk-Medium.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "/fonts/clash-grotesk/ClashGrotesk-Semibold.woff2",
      weight: "600",
      style: "normal",
    },
    {
      path: "/fonts/clash-grotesk/ClashGrotesk-Bold.woff2",
      weight: "700",
      style: "normal",
    },
  ],
  display: "swap",
});

export const metadata = {
  title: "Portify",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* <SmoothScroll> */}
        <body
          className={`${clashGrotesk.className} antialiased bg-zinc100 text-zinc800 leading-[130%]`}
        >
          <Navbar />
          {/* <PageTransition> */}
          <main className="w-full">{children}</main>
          {/* </PageTransition> */}
          {/* <Footer /> */}
        </body>
      {/* </SmoothScroll> */}
    </html>
  );
}
